<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-SensorFacebook.Scheduler-59322795-de02-457a-84d0-6edd44781f7c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire" Version="1.8.22" />
    <PackageReference Include="Hangfire.Redis.StackExchange" Version="1.12.0" />
    <PackageReference Include="MassTransit" Version="8.5.5" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="prometheus-net" Version="8.2.1" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.0" />
    <PackageReference Include="StackExchange.Redis" Version="2.9.32" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SensorFacebook.Application\SensorFacebook.Application.csproj" />
    <ProjectReference Include="..\SensorFacebook.Infrastructure\SensorFacebook.Infrastructure.csproj" />
    <ProjectReference Include="..\SensorFacebook.Shared\SensorFacebook.Shared.csproj" />
  </ItemGroup>
</Project>
